<?php
/**
 * Created by PhpStorm.
 * User: kranthi
 * Date: 26/6/18
 * Time: 10:28 PM
 */

class Extension extends Twig_Loader_Filesystem
{
    protected function findTemplate($name)
    {
        //echo "stop me".__FILE__.$name;die;
        $name .= ".html.twig";
        return parent::findTemplate($name); // TODO: Change the autogenerated stub
    }

}